[workspace]
members = ["crates/*", "src-tauri"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"

[workspace.dependencies]
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sm-domain = { path = "crates/sm-domain" }
sm-infra = { path = "crates/sm-infra" }
