[package]
name = "sm-infra"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sm-domain = { path = "../sm-domain" }

[target.'cfg(target_os = "windows")'.dependencies]
windows-capture = "2"

[target.'cfg(target_os = "macos")'.dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
